databases:
  TRI:
    url: https://www.epa.gov/toxics-release-inventory-tri-program/tri-basic-plus-data-files-calendar-years-1987-2017
    queries:
      TRI_year_reported: 'option'
      TRI_zip: 'value'
  RCRAInfo:
    url: https://rcrapublic.epa.gov/rcra-public-export
    queries:
      Table_of_tables: "//table[@id='tables']"
  eGRID:
    url: https://www.epa.gov/egrid/emissions-generation-resource-integrated-database-egrid
    '2014':
        file_name: 'eGRID2014_Data_v2.xlsx'
        file_version: 'v2'
        download_url: 'https://www.epa.gov/sites/production/files/2020-01/egrid2018_historical_files_since_1996.zip'
    '2016':
        file_name: 'egrid2016_data.xlsx'
        file_version: ''
        download_url: 'https://www.epa.gov/sites/production/files/2020-01/egrid2018_historical_files_since_1996.zip'
    '2018':
        file_name: 'eGRID2018_Data_v2.xlsx'
        file_version: 'v2'
        download_url: 'https://www.epa.gov/sites/production/files/2020-03/egrid2018_data_v2.xlsx'
    '2019':
        file_name: 'eGRID2019_data.xlsx'
        file_version: ''
        download_url: 'https://www.epa.gov/sites/production/files/2021-02/egrid2019_data.xlsx'
  NEI:
    url: 'http://eis.epa.gov'
    '2011':
        file_name:
            - 'NEI/2011NEIv3_R1-3/emis_sum_proc_5906.csv'
            - 'NEI/2011NEIv3_R4-6/emis_sum_proc_5907.csv'
            - 'NEI/2011NEIv3_R7-10/emis_sum_proc_5908.csv'
        file_version: 'v3'
    '2014':
        file_name:
            - 'NEI/2014_NEI_V2_R1-3/emis_sum_proc_6033.csv'
            - 'NEI/2014_NEI_V2_R4-6/emis_sum_proc_6034.csv'
            - 'NEI/2014_NEI_V2_R7-10/emis_sum_proc_6035.csv'
        file_version: 'v2'
    '2016':
        file_name:
            - '../NEI/2016_NEI_R1-3/emis_sum_proc_5828.csv'
            - '../NEI/2016_NEI_R4-6/emis_sum_proc_5829.csv'
            - '../NEI/2016_NEI_R7-10/emis_sum_proc_5830.csv'
        file_version: ''
    '2017':
        file_name: 
            - 'sppd_rtr_13595.csv'
            - 'sppd_rtr_13597.csv'
            - 'sppd_rtr_13602.csv'
        file_version: 'v1'
    national_url: 'ftp://newftp.epa.gov/air/nei/__year__/data_summaries/__version___facility.zip'
    national_version:
        '2017': '2017v1/2017neiApr'
        '2014': '2014v2/2014neiv2'
        '2011': '2011v2/2011neiv2'
  DMR:
      url: 'https://echo.epa.gov/trends/loading-tool/water-pollution-search'
      base_url: 'https://ofmpub.epa.gov/echo/dmr_rest_services.get_custom_data_annual?'
      pollutant_list_url: 'https://ofmpub.epa.gov/echo/dmr_rest_services.get_loading_tool_params?output=csv'
      state_url: 'https://ofmpub.epa.gov/echo/dmr_rest_services.get_state_stats?p_year=__year__&output=csv'
  GHGRP:
      most_recent_year: '2019'
      enviro_url: 'https://data.epa.gov/efservice/'
      url: 'https://www.epa.gov/sites/production/files/2020-11/'
      data_summaries_url: '2019_data_summary_spreadsheets.zip'
        # Data Summary Spreadsheets: .zip file containing multi-year spreadsheets containing
        # the most important high-level information for facilities, as well as yearly
        # spreadsheets containing slightly more detailed information, including
        # reported emissions by greenhouse gas and process.
      esbb_subparts_url: 'e_s_cems_bb_cc_ll_full_data_set_10_21_2020.xlsx'
        # Subparts E, S-CEMS, BB, CC, LL Data Set: .xlsx file containing publicly available data
        # reported by facilities in the following industries across all reporting years:
        # Adipic Acid Production (E), Lime Manufacturing (S, CEMS reporters only), 
        # Silicon Carbide Production (BB), Soda Ash Manufacturing (CC) and 
        # Coal-based Liquid Fuel Suppliers (LL).
        # LL is not included because it is a supplier, rather than an emitter.
      lo_subparts_url: 'ghgp_l_o_freq_request_data_10_2020.xlsx'
        # Subparts L, O Data Set: .xlsx file containing publicly available data
        # reported by facilities under: 
        # Subpart L (Fluorinated Gas Production) and 
        # Subpart O (HCFC-22 Production and HFC-23 Destruction)
        # across all reporting years.
      subpart_L_GWPs_url: 'https://ccdsupport.com/confluence/download/attachments/63996073/Subpart%20L%20Calculation%20Spreadsheet%20-%20Summarize%20Process%20Level%20CO2e%20by%20f-GHG.xls?version=1&modificationDate=1427459649000&api=v2'

