databases:
  SRS:
    url: https://cdxapps.epa.gov/oms-substance-registry-services/rest-api/
    # see https://cdxapps.epa.gov/oms-substance-registry-services/swagger-ui/
    queries:
      caslistprefix: substances/cas?casList=
      nameprefix: substance/name/
      listprefix: substances/list_acronym/
      sep: '%7c'
    inventory_lists:
      RCRAInfo:
          - 'RCRA F Waste'
          - 'RCRA U Waste'
          - 'RCRA K Waste'
          - 'RCRA P Waste'
          - 'RCRA T Char'
      TRI:
          - 'TRIPS'
      NEI:
          - 'EIS'
      DMR:
          - 'PCS'
          - 'ICIS'
          - 'NPDES'
